In [1]:
import pandas as pd
import numpy as np

In [2]:
crime_2008 = pd.read_csv("Crime_Incidents_in_2008.csv")
crime_2009 = pd.read_csv("Crime_Incidents_in_2009.csv")
crime_2010 = pd.read_csv("Crime_Incidents_in_2010.csv")
crime_2011 = pd.read_csv("Crime_Incidents_in_2011.csv")
crime_2012 = pd.read_csv("Crime_Incidents_in_2012.csv")
crime_2013 = pd.read_csv("Crime_Incidents_in_2013.csv")
crime_2014 = pd.read_csv("Crime_Incidents_in_2014.csv")
crime_2015 = pd.read_csv("Crime_Incidents_in_2015.csv")
crime_2016 = pd.read_csv("Crime_Incidents_in_2016.csv")
crime_2017 = pd.read_csv("Crime_Incidents_in_2017.csv")
crime_2018 = pd.read_csv("Crime_Incidents_in_2018.csv")
crime_2019 = pd.read_csv("Crime_Incidents_in_2019.csv")

In [3]:
crime_2016.head()

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,BLOCK_GROUP,CENSUS_TRACT,VOTING_PRECINCT,LATITUDE,LONGITUDE,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID
0,-76.997328,38.885141,1020310,2016-02-09T13:46:39.000Z,DAY,OTHERS,THEFT/OTHER,600 - 669 BLOCK OF PENNSYLVANIA AVENUE SE,400232,135255,...,006500 1,6500.0,Precinct 89,38.885133,-76.997326,CAPITOL HILL,2016-01-19T17:00:03.000Z,2016-01-28T10:00:10.000Z,326472405,01020310-01
1,-76.969243,38.851752,6021842,2016-02-12T13:31:08.000Z,DAY,OTHERS,THEFT/OTHER,2600 - 2799 BLOCK OF JASPER STREET SE,402670,131549,...,007408 1,7408.0,Precinct 115,38.851744,-76.969241,NaN,2016-02-06T18:30:37.000Z,2016-02-06T18:40:51.000Z,326472412,06021842-01
2,-77.065954,38.948361,6080644,2016-05-20T19:04:31.000Z,EVENING,OTHERS,THEFT/OTHER,4500 - 4529 BLOCK OF CONNECTICUT AVENUE NW,394283,142275,...,001200 2,1200.0,Precinct 33,38.948353,-77.065951,NaN,2016-05-11T11:00:13.000Z,2016-05-16T10:00:24.000Z,326873629,06080644-01
3,-76.952700,38.919922,10151260,2016-09-07T14:13:47.000Z,DAY,OTHERS,THEFT F/AUTO,2400 - 2499 BLOCK OF MARKET STREET NE,404102,139117,...,009000 1,9000.0,Precinct 139,38.919914,-76.952698,NaN,2016-09-07T14:00:24.000Z,2016-09-07T14:12:47.000Z,326952058,10151260-01
4,-76.987356,38.898536,10205222,2016-12-04T03:11:26.000Z,MIDNIGHT,OTHERS,THEFT F/AUTO,1300 - 1353 BLOCK OF MARYLAND AVENUE NE,401097,136742,...,008402 1,8402.0,Precinct 82,38.898528,-76.987354,NaN,2016-12-03T20:00:00.000Z,2016-12-04T02:00:44.000Z,326957236,10205222-01

In [4]:
crime_total = [crime_2008, crime_2009, crime_2010, crime_2011, crime_2012, crime_2013, crime_2014, crime_2015, crime_2016, crime_2017, crime_2018, crime_2019]
merged_crime = pd.concat(crime_total, sort=False)

In [5]:
merged_crime.sort_values(by=['START_DATE'])

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,BLOCK_GROUP,CENSUS_TRACT,VOTING_PRECINCT,LATITUDE,LONGITUDE,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID
2994,-77.041369,38.906069,14007964,2014-01-17T09:55:00.000Z,DAY,OTHERS,THEFT/OTHER,1200 - 1219 BLOCK OF CONNECTICUT AVENUE NW,396412.0,137579.0,...,010700 2,10700.0,Precinct 17,38.906062,-77.041367,GOLDEN TRIANGLE,1800-01-16T09:51:02.000Z,2014-01-17T09:55:00.000Z,329084931,14007964-01
20894,-76.991019,38.830514,12118874,2012-08-22T22:53:00.000Z,EVENING,OTHERS,THEFT/OTHER,800 - 899 BLOCK OF MONTERIA COURT SE,400780.0,129191.0,...,009700 2,9700.0,Precinct 125,38.830506,-76.991017,NaN,1912-08-22T21:00:00.000Z,2012-08-22T20:10:00.000Z,329427659,12118874-01
22767,-77.000060,38.876484,12131446,2012-09-16T22:45:00.000Z,EVENING,OTHERS,THEFT/OTHER,400 - 499 BLOCK OF M STREET SE,399995.0,134294.0,...,007200 2,7200.0,Precinct 131,38.876476,-77.000058,CAPITOL RIVERFRONT,1912-09-16T23:40:00.000Z,2012-09-16T22:45:00.000Z,329429532,12131446-01
23627,-77.021921,38.912462,14148057,2014-09-27T07:49:00.000Z,DAY,OTHERS,THEFT/OTHER,1624 - 1699 BLOCK OF 7TH STREET NW,398099.0,138288.0,...,004901 1,4901.0,Precinct 21,38.912454,-77.021919,NaN,1914-09-26T19:00:00.000Z,2014-09-27T07:00:00.000Z,329108150,14148057-01
32738,-76.965603,38.874614,15038309,2015-03-19T15:22:00.000Z,EVENING,OTHERS,MOTOR VEHICLE THEFT,2900 - 2999 BLOCK OF N STREET SE,402985.0,134087.0,...,007709 2,7709.0,Precinct 111,38.874607,-76.965601,NaN,1915-03-18T16:00:00.000Z,2015-03-18T21:00:00.000Z,329132686,15038309-01
20461,-77.031955,38.918648,15145586,2015-09-15T13:33:26.000Z,DAY,OTHERS,THEFT/OTHER,2100 - 2199 BLOCK OF 14TH STREET NW,397229.0,138975.0,...,004300 1,4300.0,Precinct 22,38.918640,-77.031953,NaN,1915-08-30T06:00:35.000Z,2015-09-14T21:00:11.000Z,329142411,15145586-01
35153,-77.061957,38.902592,15402513,2015-12-08T14:05:08.000Z,DAY,OTHERS,THEFT/OTHER,3100 - 3199 BLOCK OF K STREET NW,394626.0,137194.0,...,000100 4,100.0,Precinct 5,38.902584,-77.061955,GEORGETOWN,1915-09-17T18:00:52.000Z,2015-09-17T18:15:56.000Z,329156471,15402513-01
23901,-76.989281,38.900203,15161356,2015-10-11T08:40:12.000Z,DAY,OTHERS,MOTOR VEHICLE THEFT,1200 - 1299 BLOCK OF H STREET NE,400930.0,136927.0,...,008402 1,8402.0,Precinct 82,38.900195,-76.989279,NaN,1915-10-10T22:30:45.000Z,2015-10-11T05:00:21.000Z,329147854,15161356-01
26645,-77.042578,38.903745,15172902,2015-10-30T21:03:20.000Z,EVENING,OTHERS,THEFT/OTHER,1800 - 1899 BLOCK OF L STREET NW,396307.0,137321.0,...,010700 1,10700.0,Precinct 17,38.903737,-77.042576,GOLDEN TRIANGLE,1915-10-16T21:03:03.000Z,NaN,329149598,15172902-01
27779,-77.070211,38.913641,15168916,2015-10-24T16:53:07.000Z,EVENING,OTHERS,THEFT F/AUTO,3500 - 3599 BLOCK OF R STREET NW,393911.0,138421.0,...,000300 1,300.0,Precinct 6,38.913633,-77.070209,NaN,1915-10-17T21:00:57.000Z,2015-10-18T06:00:03.000Z,329150732,15168916-01
6091,-76.939276,38.880982,16027878,2016-02-23T23:14:15.000Z,MIDNIGHT,OTHERS,MOTOR VEHICLE THEFT,4700 - 4799 BLOCK OF ALABAMA AVENUE SE,405269.0,134795.0,...,009907 1,9907.0,Precinct 103,38.880974,-76.939274,NaN,1916-02-15T01:30:52.000Z,1916-02-23T14:00:05.000Z,327143985,16027878-01
4587,-77.072294,38.921513,16038136,2016-03-12T16:02:12.000Z,EVENING,OTHERS,THEFT F/AUTO,2301 - 2499 BLOCK OF WISCONSIN AVENUE NW,393731.0,139295.0,...,000300 1,300.0,Precinct 11,38.921505,-77.072292,NaN,1916-03-10T10:00:00.000Z,2016-03-12T16:02:06.000Z,327142481,16038136-01
9994,-76.986569,38.915147,16061294,2016-04-19T21:44:46.000Z,EVENING,OTHERS,THEFT/OTHER,1240 - 1399 BLOCK OF NEW YORK AVENUE NE,401165.0,138586.0,...,008803 1,8803.0,Precinct 76,38.915140,-76.986567,NaN,1916-04-17T21:00:57.000Z,2016-04-18T07:00:40.000Z,327147888,16061294-01
12408,-76.990911,38.862314,16062236,2016-04-21T13:21:51.000Z,DAY,OTHERS,THEFT F/AUTO,2300 - 2399 BLOCK OF MOUNT VIEW PLACE SE,400789.0,132721.0,...,007407 2,7407.0,Precinct 119,38.862306,-76.990909,NaN,1916-04-21T12:40:44.000Z,2016-04-21T12:43:30.000Z,327150302,16062236-01
12421,-76.998620,38.826055,16064838,2016-04-25T16:36:42.000Z,EVENING,OTHERS,THEFT F/AUTO,4284 4293 BLOCK OF 6TH STREET SE,400120.0,128696.0,...,009811 1,9811.0,Precinct 125,38.826047,-76.998618,NaN,1916-04-23T22:00:13.000Z,2016-04-25T15:00:06.000Z,327150315,16064838-01
14312,-76.972782,38.845663,16073374,2016-05-09T11:44:47.000Z,DAY,OTHERS,MOTOR VEHICLE THEFT,3400 - 3683 BLOCK OF 22ND STREET SE,402363.0,130873.0,...,007409 2,7409.0,Precinct 116,38.845655,-76.972780,NaN,1916-05-08T22:00:38.000Z,1916-05-09T07:00:43.000Z,327151206,16073374-01
22630,-76.930022,38.892904,8114178,2008-08-04T00:00:00.000Z,MIDNIGHT,GUN,HOMICIDE,200 - 299 BLOCK OF 50TH STREET NE,406071.0,136119.0,...,007804 2,7804.0,Precinct 97,38.892896,-76.930019,NaN,1974-09-15T00:00:00.000Z,1974-09-15T00:00:00.000Z,328903531,08114178-01
15192,-77.041868,38.911330,17093717,2017-06-03T00:24:27.000Z,MIDNIGHT,OTHERS,SEX ABUSE,1600 - 1610 BLOCK OF NEW HAMPSHIRE AVENUE NW,396369.0,138163.0,...,005301 2,5301.0,Precinct 14,38.911322,-77.041866,NaN,1980-06-02T20:00:46.000Z,1980-06-02T20:30:56.000Z,327191273,17093717-01
38425,-77.046529,38.916391,81156414,2014-08-07T00:00:00.000Z,MIDNIGHT,GUN,HOMICIDE,1900 - 1999 BLOCK OF CONNECTICUT AVENUE NW,395965.0,138725.0,...,004100 1,4100.0,Precinct 13,38.916383,-77.046527,NaN,1981-03-30T13:45:00.000Z,1981-03-30T00:00:00.000Z,329248755,81156414-01
33633,-77.010264,38.911860,85017166,2018-02-27T00:00:00.000Z,MIDNIGHT,OTHERS,HOMICIDE,1 - 99 BLOCK OF QUINCY PLACE NW,399110.0,138221.0,...,003302 2,3302.0,Precinct 19,38.911852,-77.010262,NaN,1985-01-11T03:56:21.000Z,1985-01-11T04:00:39.000Z,314089882,85017166-01
33634,-77.010264,38.911860,85017166,2018-02-27T00:00:00.000Z,MIDNIGHT,OTHERS,HOMICIDE,1 - 99 BLOCK OF QUINCY PLACE NW,399110.0,138221.0,...,003302 2,3302.0,Precinct 19,38.911852,-77.010262,NaN,1985-01-11T03:56:21.000Z,1985-01-11T04:00:39.000Z,314089883,85017166-02
33618,-76.999311,38.845838,91603502,2018-12-10T00:00:00.000Z,MIDNIGHT,GUN,HOMICIDE,500 - 599 BLOCK OF NEWCOMB STREET SE,400060.0,130892.0,...,010400 2,10400.0,Precinct 123,38.845830,-76.999309,NaN,1991-10-30T00:41:20.000Z,1991-10-30T01:00:44.000Z,314088460,91603502-01
34267,-76.983549,38.909688,93629714,2008-11-06T00:00:00.000Z,MIDNIGHT,GUN,HOMICIDE,1200 - 1299 BLOCK OF MOUNT OLIVET ROAD NE,401427.0,137980.0,...,008804 2,8804.0,Precinct 78,38.909680,-76.983547,NaN,1993-11-01T00:00:00.000Z,1993-11-01T00:00:00.000Z,329248758,93629714-01
17695,-77.042326,38.926311,15096394,2015-06-26T20:00:00.000Z,EVENING,OTHERS,SEX ABUSE,1800 - 1899 BLOCK OF SUMMIT PLACE NW,396330.0,139826.0,...,003900 2,3900.0,Precinct 35,38.926303,-77.042324,NaN,1997-12-15T17:00:00.000Z,1997-12-31T23:59:00.000Z,329140645,15096394-01
33272,-77.040092,38.910394,99020963,2011-05-21T00:00:00.000Z,MIDNIGHT,GUN,HOMICIDE,1700 - 1799 BLOCK OF CHURCH STREET NW,396523.0,138059.0,...,005301 2,5301.0,Precinct 15,38.910386,-77.040089,NaN,1999-01-09T13:30:00.000Z,1999-01-09T00:00:00.000Z,329248759,99020963-01
35300,-77.023975,38.916281,99258578,2012-10-20T00:00:00.000Z,MIDNIGHT,OTHERS,SEX ABUSE,1900 - 1999 BLOCK OF 9TH STREET NW,397921.0,138712.0,...,004400 2,4400.0,Precinct 137,38.916273,-77.023973,NaN,1999-02-17T00:00:00.000Z,1999-02-17T00:00:00.000Z,329664768,99258578-01
31306,-76.939207,38.895197,99438989,2009-06-23T00:00:00.000Z,MIDNIGHT,OTHERS,HOMICIDE,400 - 499 BLOCK OF 44TH STREET NE,405274.0,136373.0,...,007803 4,7803.0,Precinct 99,38.895189,-76.939204,NaN,1999-08-01T04:00:00.000Z,1999-08-02T00:00:00.000Z,329664769,99438989-01
1348,-76.989554,38.844495,8000425,2008-01-01T19:00:00.000Z,EVENING,OTHERS,ROBBERY,1200 - 1299 BLOCK OF ALABAMA AVENUE SE,400907.0,130743.0,...,010400 2,10400.0,Precinct 119,38.844487,-76.989552,NaN,2000-01-01T15:40:00.000Z,2000-01-01T15:42:00.000Z,328882245,08000425-01
1752,-76.964589,38.851562,8005131,2008-01-12T00:45:00.000Z,MIDNIGHT,OTHERS,BURGLARY,3000 - 3099 BLOCK OF 30TH STREET SE,403074.0,131528.0,...,007408 1,7408.0,Precinct 115,38.851554,-76.964586,NaN,2000-01-11T15:00:00.000Z,2008-01-11T21:00:00.000Z,328882649,08005131-01
533,-77.011195,38.895455,9009377,2009-01-20T23:59:00.000Z,MIDNIGHT,OTHERS,ROBBERY,400 - 499 BLOCK OF NEW JERSEY AVENUE NW,399029.0,136400.0,...,005900 1,5900.0,Precinct 1,38.895448,-77.011193,DOWNTOWN,2000-01-20T22:35:00.000Z,2009-01-20T22:37:00.000Z,329311038,09009377-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18581,-76.963526,38.880244,19142479,2019-08-12T22:20:07.000Z,EVENING,OTHERS,BURGLARY,3010 - 3099 BLOCK OF G STREET SE,403165.0,134712.0,...,007709 1,7709.0,Precinct 132,38.880236,-76.963523,NaN,2019-08-12T19:01:28.000Z,2019-08-12T22:10:22.000Z,327266694,19142479-01
18585,-77.032733,38.929521,19142489,2019-08-13T00:04:27.000Z,MIDNIGHT,OTHERS,THEFT/OTHER,3100 - 3299 BLOCK OF 14TH STREET NW,397162.0,140182.0,...,003000 1,3000.0,Precinct 39,38.929513,-77.032731,NaN,2019-08-12T19:40:03.000Z,2019-08-12T21:08:57.000Z,327266698,19142489-01
18588,-77.013664,38.906112,19142510,2019-08-12T21:30:23.000Z,EVENING,OTHERS,THEFT F/AUTO,1200 - 1209 BLOCK OF KIRBY STREET NW,398815.0,137583.0,...,004600 2,4600.0,Precinct 1,38.906104,-77.013662,NaN,2019-08-12T19:41:51.000Z,2019-08-12T20:48:47.000Z,327266701,19142510-01
18589,-77.019904,38.914777,19142513,2019-08-12T20:46:23.000Z,EVENING,OTHERS,THEFT/OTHER,1800 - 1841 BLOCK OF 6TH STREET NW,398274.0,138545.0,...,004801 1,4801.0,Precinct 21,38.914769,-77.019902,NaN,2019-08-12T20:07:46.000Z,2019-08-12T20:40:30.000Z,327266702,19142513-01
18587,-77.039673,38.903151,19142507,2019-08-12T20:56:03.000Z,EVENING,OTHERS,THEFT/OTHER,1000 - 1099 BLOCK OF CONNECTICUT AVENUE NW,396559.0,137255.0,...,010700 1,10700.0,Precinct 17,38.903143,-77.039670,GOLDEN TRIANGLE,2019-08-12T20:10:07.000Z,2019-08-12T20:11:58.000Z,327266700,19142507-01
18590,-76.955144,38.922283,19142516,2019-08-12T20:45:24.000Z,EVENING,OTHERS,THEFT/OTHER,2400 - 2432 BLOCK OF BALDWIN CRESCENT NE,403890.0,139379.0,...,009000 1,9000.0,Precinct 139,38.922275,-76.955141,NaN,2019-08-12T20:17:43.000Z,NaN,327266703,19142516-01
18719,-76.988435,38.854179,19142557,2019-08-13T00:00:00.000Z,MIDNIGHT,GUN,HOMICIDE,2400 - 2599 BLOCK OF ELVANS ROAD SE,401004.0,131818.0,...,007406 2,7406.0,Precinct 118,38.854171,-76.988433,NaN,2019-08-12T20:25:00.000Z,2019-08-12T23:12:47.000Z,327266832,19142557-01
18718,-77.037465,38.935717,19142536,2019-08-12T21:36:55.000Z,EVENING,OTHERS,THEFT/OTHER,1610 - 1699 BLOCK OF OAK STREET NW,396752.0,140870.0,...,002701 1,2701.0,Precinct 40,38.935709,-77.037462,NaN,2019-08-12T20:36:45.000Z,2019-08-12T21:24:24.000Z,327266831,19142536-01
18591,-77.018933,38.906048,19142528,2019-08-12T21:46:55.000Z,EVENING,OTHERS,THEFT/OTHER,1200 - 1220 BLOCK OF 5TH STREET NW,398358.0,137576.0,...,004802 2,4802.0,Precinct 18,38.906040,-77.018931,NaN,2019-08-12T20:51:44.000Z,2019-08-12T21:16:31.000Z,327266704,19142528-01
18723,-77.016777,38.953234,19142579,2019-08-12T22:50:10.000Z,EVENING,OTHERS,THEFT/OTHER,300 - 399 BLOCK OF HAMILTON STREET NW,398546.0,142814.0,...,002102 5,2102.0,Precinct 57,38.953226,-77.016775,NaN,2019-08-12T21:00:55.000Z,2019-08-12T21:40:18.000Z,327266836,19142579-01
18722,-77.000060,38.876484,19142572,2019-08-12T22:20:54.000Z,EVENING,OTHERS,THEFT/OTHER,400 - 499 BLOCK OF M STREET SE,399995.0,134294.0,...,007200 2,7200.0,Precinct 131,38.876476,-77.000058,CAPITOL RIVERFRONT,2019-08-12T21:15:20.000Z,2019-08-12T21:22:19.000Z,327266835,19142572-01
18721,-76.938599,38.891125,19142571,2019-08-13T00:39:56.000Z,MIDNIGHT,OTHERS,THEFT/OTHER,4400 - 4499 BLOCK OF BENNING ROAD NE,405327.0,135921.0,...,009603 1,9603.0,Precinct 102,38.891117,-76.938597,NaN,2019-08-12T21:39:38.000Z,2019-08-12T22:28:16.000Z,327266834,19142571-01
18725,-76.972782,38.845663,19142594,2019-08-12T23:34:46.000Z,MIDNIGHT,OTHERS,THEFT/OTHER,3400 - 3683 BLOCK OF 22ND STREET SE,402363.0,130873.0,...,007409 2,7409.0,Precinct 116,38.845655,-76.972780,NaN,2019-08-12T21:41:43.000Z,2019-08-12T23:09:58.000Z,327266838,19142594-01
18720,-77.028858,38.900488,19142569,2019-08-12T22:27:01.000Z,EVENING,OTHERS,THEFT/OTHER,1200 - 1299 BLOCK OF NEW YORK AVENUE NW,397497.0,136959.0,...,010100 1,10100.0,Precinct 129,38.900480,-77.028855,DOWNTOWN,2019-08-12T21:44:30.000Z,2019-08-12T22:27:15.000Z,327266833,19142569-01
18724,-77.031955,38.917558,19142593,2019-08-12T23:10:37.000Z,MIDNIGHT,KNIFE,ROBBERY,2000 - 2099 BLOCK OF 14TH STREET NW,397229.0,138854.0,...,004300 1,4300.0,Precinct 22,38.917550,-77.031952,NaN,2019-08-12T22:20:55.000Z,2019-08-12T22:45:48.000Z,327266837,19142593-01
18726,-76.977358,38.871383,19142604,2019-08-13T00:22:02.000Z,MIDNIGHT,GUN,ASSAULT W/DANGEROUS WEAPON,1500 - 1599 BLOCK OF 19TH STREET SE,401965.0,133728.0,...,007601 3,7601.0,Precinct 140,38.871375,-76.977356,NaN,2019-08-12T22:26:36.000Z,NaN,327266839,19142604-01
18727,-77.001453,38.825091,19142616,2019-08-13T00:21:09.000Z,MIDNIGHT,OTHERS,ROBBERY,4400 - 4599 BLOCK OF 3RD STREET SE,399874.0,128589.0,...,009810 1,9810.0,Precinct 125,38.825083,-77.001451,NaN,2019-08-12T23:04:20.000Z,NaN,327266840,19142616-01
31929,-76.988174,38.903049,8252677,2008-05-02T20:59:00.000Z,EVENING,OTHERS,ASSAULT W/DANGEROUS WEAPON,1200 - 1299 BLOCK OF MORSE STREET NE,401026.0,137243.0,...,008802 3,8802.0,Precinct 77,38.903042,-76.988172,NaN,NaN,NaN,328914834,08252677-01
31930,-77.001305,38.916283,8252683,2008-05-04T00:00:00.000Z,MIDNIGHT,OTHERS,ASSAULT W/DANGEROUS WEAPON,300 - 399 BLOCK OF TODD PLACE NE,399887.0,138712.0,...,008702 1,8702.0,Precinct 75,38.916275,-77.001303,NaN,NaN,NaN,328914835,08252683-01
31939,-76.987102,38.902013,8254716,2008-10-04T00:00:00.000Z,MIDNIGHT,OTHERS,THEFT/OTHER,1100 - 1199 BLOCK OF TRINIDAD AVENUE NE,401119.0,137128.0,...,008802 2,8802.0,Precinct 77,38.902005,-76.987100,NaN,NaN,NaN,328914845,08254716-01
29815,-77.012911,38.820433,9250788,2009-06-01T00:00:00.000Z,MIDNIGHT,OTHERS,ASSAULT W/DANGEROUS WEAPON,4600 - 4699 BLOCK OF BLUE PLAINS DRIVE SW,398879.0,128072.0,...,010900 2,10900.0,Precinct 126,38.820425,-77.012909,NaN,NaN,NaN,329341350,09250788-01
29821,-77.003595,38.826460,9252517,2009-04-19T00:00:00.000Z,MIDNIGHT,OTHERS,ROBBERY,4180 - 4530 BLOCK OF LIVINGSTON ROAD SE,399688.0,128741.0,...,009810 1,9810.0,Precinct 125,38.826453,-77.003593,NaN,NaN,NaN,329341358,09252517-01
20116,-76.988435,38.854179,10121712,2010-08-24T01:25:00.000Z,MIDNIGHT,GUN,ASSAULT W/DANGEROUS WEAPON,2400 - 2599 BLOCK OF ELVANS ROAD SE,401004.0,131818.0,...,007406 2,7406.0,Precinct 118,38.854171,-76.988433,NaN,NaN,2010-08-23T22:45:00.000Z,328966582,10121712-01
15910,-77.023362,38.981717,11100319,2011-07-13T08:54:00.000Z,DAY,OTHERS,THEFT/OTHER,700 - 709 BLOCK OF HEMLOCK STREET NW,397976.0,145976.0,...,010300 2,10300.0,Precinct 63,38.981709,-77.023360,NaN,NaN,2011-07-13T07:35:00.000Z,328996024,11100319-01
31136,-76.978818,38.846782,11250714,2011-05-17T00:00:00.000Z,MIDNIGHT,OTHERS,ROBBERY,3300 - 3399 BLOCK OF 18TH STREET SE,401839.0,130997.0,...,007403 1,7403.0,Precinct 116,38.846774,-76.978815,NaN,NaN,NaN,329012567,11250714-01
31137,-76.986569,38.915147,11250969,2011-02-26T00:00:00.000Z,MIDNIGHT,OTHERS,SEX ABUSE,1240 - 1399 BLOCK OF NEW YORK AVENUE NE,401165.0,138586.0,...,008803 1,8803.0,Precinct 76,38.915140,-76.986567,NaN,NaN,NaN,329012568,11250969-01
34752,-77.021899,38.916263,12251352,2012-06-29T00:00:00.000Z,MIDNIGHT,KNIFE,SEX ABUSE,FLORIDA AVENUE NW AND GEORGIA AVENUE NW,398101.0,138710.0,...,003500 2,3500.0,Precinct 137,38.916255,-77.021897,NaN,NaN,NaN,329441254,12251352-01
21411,-76.986094,38.866952,13123903,2013-08-30T22:45:00.000Z,EVENING,OTHERS,THEFT/OTHER,1300 - 1399 BLOCK OF GOOD HOPE ROAD SE,401207.0,133236.0,...,007503 1,7503.0,Precinct 114,38.866945,-76.986092,ANACOSTIA,NaN,2013-08-30T22:14:00.000Z,329069090,13123903-01
12946,-77.005600,38.840432,14079438,2014-06-02T22:00:00.000Z,EVENING,OTHERS,MOTOR VEHICLE THEFT,3500 - 3599 BLOCK OF BROTHERS PLACE SE,399514.0,130292.0,...,010400 1,10400.0,Precinct 124,38.840425,-77.005598,NaN,NaN,2014-06-03T04:30:00.000Z,329097469,14079438-01
2365,-77.074649,38.934294,15007014,2015-01-15T11:25:00.000Z,DAY,OTHERS,SEX ABUSE,3300 - 3399 BLOCK OF IDAHO AVENUE NW,393528.0,140714.0,...,001002 2,1002.0,Precinct 29,38.934286,-77.074646,NaN,NaN,NaN,329123764,15007014-01

In [6]:
new = merged_crime["START_DATE"].str.split("-", expand = True)
new.head()

      0   1                 2
0  2008  01  14T00:05:00.000Z
1  2008  01  13T17:00:00.000Z
2  2008  01  14T05:15:00.000Z
3  2008  01  13T19:00:00.000Z
4  2008  01  14T07:00:00.000Z

In [7]:
# new[0].value_counts()
merged_crime["report_year"] = new[0]

In [8]:
merged_crime.head()

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,CENSUS_TRACT,VOTING_PRECINCT,LATITUDE,LONGITUDE,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID,report_year
0,-76.986374,38.909968,8006028,2008-01-14T04:00:00.000Z,MIDNIGHT,OTHERS,BURGLARY,1700 - 1799 BLOCK OF WEST VIRGINIA AVENUE NE,401182.0,138011.0,...,8803.0,Precinct 76,38.909960,-76.986372,NaN,2008-01-14T00:05:00.000Z,2008-01-14T01:30:00.000Z,328882875,08006028-01,2008
1,-76.988174,38.903049,8006037,2008-01-14T05:55:00.000Z,MIDNIGHT,OTHERS,THEFT/OTHER,1200 - 1299 BLOCK OF MORSE STREET NE,401026.0,137243.0,...,8802.0,Precinct 77,38.903042,-76.988172,NaN,2008-01-13T17:00:00.000Z,2008-01-14T04:30:00.000Z,328882876,08006037-01,2008
2,-76.972782,38.845663,8006042,2008-01-14T06:00:00.000Z,MIDNIGHT,GUN,ROBBERY,3400 - 3683 BLOCK OF 22ND STREET SE,402363.0,130873.0,...,7409.0,Precinct 116,38.845655,-76.972780,NaN,2008-01-14T05:15:00.000Z,2008-01-14T00:00:00.000Z,328882877,08006042-01,2008
3,-77.031561,38.966131,8006047,2008-01-14T07:19:00.000Z,DAY,OTHERS,THEFT/OTHER,1300 - 1399 BLOCK OF SHERIDAN STREET NW,397265.0,144246.0,...,1804.0,Precinct 60,38.966123,-77.031559,NaN,2008-01-13T19:00:00.000Z,2008-01-14T07:00:00.000Z,328882878,08006047-01,2008
4,-77.031813,38.935295,8006048,2008-01-14T09:27:00.000Z,DAY,OTHERS,THEFT/OTHER,1300 - 1399 BLOCK OF PARKWOOD PLACE NW,397242.0,140823.0,...,2900.0,Precinct 41,38.935288,-77.031810,NaN,2008-01-14T07:00:00.000Z,2008-01-14T09:27:00.000Z,328882879,08006048-01,2008

In [9]:
merged_crime.dropna(subset=['START_DATE', 'report_year'], inplace=True)
merged_crime['report_year']= merged_crime['report_year'].astype(int)

In [10]:
merged_crime = merged_crime[merged_crime.report_year >= 2008]

In [11]:
merged_crime['report_year'].value_counts()

2014    38379
2015    37359
2016    37146
2013    35897
2012    35232
2008    34236
2018    33641
2011    33346
2017    33002
2010    31706
2009    31282
2019    19473
Name: report_year, dtype: int64

In [12]:
# merged_crime['START_DATE']= merged_crime['START_DATE'].astype(str)

In [13]:
merged_crime['START_DATE']= merged_crime['START_DATE'].map(lambda x: str(x)[:-14])

In [14]:
merged_crime.head()

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,CENSUS_TRACT,VOTING_PRECINCT,LATITUDE,LONGITUDE,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID,report_year
0,-76.986374,38.909968,8006028,2008-01-14T04:00:00.000Z,MIDNIGHT,OTHERS,BURGLARY,1700 - 1799 BLOCK OF WEST VIRGINIA AVENUE NE,401182.0,138011.0,...,8803.0,Precinct 76,38.909960,-76.986372,NaN,2008-01-14,2008-01-14T01:30:00.000Z,328882875,08006028-01,2008
1,-76.988174,38.903049,8006037,2008-01-14T05:55:00.000Z,MIDNIGHT,OTHERS,THEFT/OTHER,1200 - 1299 BLOCK OF MORSE STREET NE,401026.0,137243.0,...,8802.0,Precinct 77,38.903042,-76.988172,NaN,2008-01-13,2008-01-14T04:30:00.000Z,328882876,08006037-01,2008
2,-76.972782,38.845663,8006042,2008-01-14T06:00:00.000Z,MIDNIGHT,GUN,ROBBERY,3400 - 3683 BLOCK OF 22ND STREET SE,402363.0,130873.0,...,7409.0,Precinct 116,38.845655,-76.972780,NaN,2008-01-14,2008-01-14T00:00:00.000Z,328882877,08006042-01,2008
3,-77.031561,38.966131,8006047,2008-01-14T07:19:00.000Z,DAY,OTHERS,THEFT/OTHER,1300 - 1399 BLOCK OF SHERIDAN STREET NW,397265.0,144246.0,...,1804.0,Precinct 60,38.966123,-77.031559,NaN,2008-01-13,2008-01-14T07:00:00.000Z,328882878,08006047-01,2008
4,-77.031813,38.935295,8006048,2008-01-14T09:27:00.000Z,DAY,OTHERS,THEFT/OTHER,1300 - 1399 BLOCK OF PARKWOOD PLACE NW,397242.0,140823.0,...,2900.0,Precinct 41,38.935288,-77.031810,NaN,2008-01-14,2008-01-14T09:27:00.000Z,328882879,08006048-01,2008

In [15]:
crime_count = merged_crime.groupby('START_DATE')['CCN'].count()
crime_count

START_DATE
2008-01-01     66
2008-01-02     66
2008-01-03     75
2008-01-04     65
2008-01-05     88
2008-01-06     63
2008-01-07     87
2008-01-08     88
2008-01-09     81
2008-01-10     56
2008-01-11     82
2008-01-12     75
2008-01-13     90
2008-01-14     64
2008-01-15     94
2008-01-16     73
2008-01-17     82
2008-01-18    112
2008-01-19     92
2008-01-20     76
2008-01-21     82
2008-01-22     97
2008-01-23     98
2008-01-24    100
2008-01-25    100
2008-01-26    110
2008-01-27     93
2008-01-28    106
2008-01-29    108
2008-01-30     80
             ...
2019-07-14     99
2019-07-15    110
2019-07-16     84
2019-07-17     97
2019-07-18     73
2019-07-19     89
2019-07-20     95
2019-07-21     88
2019-07-22    114
2019-07-23     96
2019-07-24    104
2019-07-25    106
2019-07-26    122
2019-07-27    118
2019-07-28    109
2019-07-29    106
2019-07-30    123
2019-07-31     90
2019-08-01     77
2019-08-02     85
2019-08-03     92
2019-08-04     90
2019-08-05    108
2019-08-06     90
2019-08-07     98
2019-08-08     95
2019-08-09     94
2019-08-10     85
2019-08-11     78
2019-08-12     93
Name: CCN, Length: 4242, dtype: int64

In [16]:
# merged_crime.to_csv("crime_08_19.csv", index=False)

In [17]:
crime_date_count = merged_crime.groupby('START_DATE')['CCN'].nunique()
crime_date_count_df = pd.DataFrame(crime_date_count)
crime_date_count_df.head()

            CCN
START_DATE
2008-01-01   66
2008-01-02   66
2008-01-03   75
2008-01-04   65
2008-01-05   88

In [18]:
crime_date_count_df.rename(columns={'CCN': 'crime-count'})

            crime-count
START_DATE
2008-01-01           66
2008-01-02           66
2008-01-03           75
2008-01-04           65
2008-01-05           88
2008-01-06           63
2008-01-07           87
2008-01-08           88
2008-01-09           79
2008-01-10           56
2008-01-11           82
2008-01-12           75
2008-01-13           90
2008-01-14           64
2008-01-15           94
2008-01-16           73
2008-01-17           82
2008-01-18          112
2008-01-19           92
2008-01-20           76
2008-01-21           82
2008-01-22           97
2008-01-23           98
2008-01-24          100
2008-01-25          100
2008-01-26          110
2008-01-27           93
2008-01-28          106
2008-01-29          108
2008-01-30           80
...                 ...
2019-07-14           99
2019-07-15          110
2019-07-16           84
2019-07-17           97
2019-07-18           73
2019-07-19           88
2019-07-20           95
2019-07-21           88
2019-07-22          114
2019-07-23           96
2019-07-24          104
2019-07-25          106
2019-07-26          122
2019-07-27          118
2019-07-28          109
2019-07-29          106
2019-07-30          123
2019-07-31           90
2019-08-01           77
2019-08-02           85
2019-08-03           92
2019-08-04           90
2019-08-05          108
2019-08-06           90
2019-08-07           98
2019-08-08           95
2019-08-09           94
2019-08-10           85
2019-08-11           78
2019-08-12           93

[4242 rows x 1 columns]

In [19]:
crime_date_count_df.reset_index()

      START_DATE  CCN
0     2008-01-01   66
1     2008-01-02   66
2     2008-01-03   75
3     2008-01-04   65
4     2008-01-05   88
5     2008-01-06   63
6     2008-01-07   87
7     2008-01-08   88
8     2008-01-09   79
9     2008-01-10   56
10    2008-01-11   82
11    2008-01-12   75
12    2008-01-13   90
13    2008-01-14   64
14    2008-01-15   94
15    2008-01-16   73
16    2008-01-17   82
17    2008-01-18  112
18    2008-01-19   92
19    2008-01-20   76
20    2008-01-21   82
21    2008-01-22   97
22    2008-01-23   98
23    2008-01-24  100
24    2008-01-25  100
25    2008-01-26  110
26    2008-01-27   93
27    2008-01-28  106
28    2008-01-29  108
29    2008-01-30   80
...          ...  ...
4212  2019-07-14   99
4213  2019-07-15  110
4214  2019-07-16   84
4215  2019-07-17   97
4216  2019-07-18   73
4217  2019-07-19   88
4218  2019-07-20   95
4219  2019-07-21   88
4220  2019-07-22  114
4221  2019-07-23   96
4222  2019-07-24  104
4223  2019-07-25  106
4224  2019-07-26  122
4225  2019-07-27  118
4226  2019-07-28  109
4227  2019-07-29  106
4228  2019-07-30  123
4229  2019-07-31   90
4230  2019-08-01   77
4231  2019-08-02   85
4232  2019-08-03   92
4233  2019-08-04   90
4234  2019-08-05  108
4235  2019-08-06   90
4236  2019-08-07   98
4237  2019-08-08   95
4238  2019-08-09   94
4239  2019-08-10   85
4240  2019-08-11   78
4241  2019-08-12   93

[4242 rows x 2 columns]

In [20]:
crime_date_count_df.to_csv("crime_counts_08_19.csv")

In [21]:
crime_df = crime_date_count_df
lunar_df = pd.read_csv("lunar_clean_08-20_sw_sw.csv")
weather_df = pd.read_csv("weather_2008_2019_complete.csv")

In [22]:
weather_df.head()

,STATION,NAME,DATE,AWND,PRCP,SNOW,SNWD,TMAX,TMIN,WDF2,...,WT09,WT11,WT13,WT14,WT15,WT16,WT17,WT18,WT21,WT22
0,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",2008-01-01,13.42,0.0,0.0,0.0,54,36,300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",2008-01-02,18.34,0.0,0.0,0.0,38,25,330,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
2,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",2008-01-03,10.74,0.0,0.0,0.0,34,22,330,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",2008-01-04,5.82,0.0,0.0,0.0,41,21,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",2008-01-05,3.58,0.0,0.0,0.0,43,28,160,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN

In [23]:
weather_df.isnull().any()

STATION    False
NAME       False
DATE       False
AWND       False
PRCP       False
SNOW       False
SNWD       False
TMAX       False
TMIN       False
WDF2       False
WDF5       False
WSF2       False
WSF5       False
WT01       False
WT02        True
WT03        True
WT04        True
WT05        True
WT06        True
WT07        True
WT08        True
WT09        True
WT11        True
WT13        True
WT14        True
WT15        True
WT16        True
WT17        True
WT18        True
WT21        True
WT22        True
dtype: bool

In [24]:
weather_df.fillna(0, inplace=True)

In [25]:
weather_df.isnull().any()

STATION    False
NAME       False
DATE       False
AWND       False
PRCP       False
SNOW       False
SNWD       False
TMAX       False
TMIN       False
WDF2       False
WDF5       False
WSF2       False
WSF5       False
WT01       False
WT02       False
WT03       False
WT04       False
WT05       False
WT06       False
WT07       False
WT08       False
WT09       False
WT11       False
WT13       False
WT14       False
WT15       False
WT16       False
WT17       False
WT18       False
WT21       False
WT22       False
dtype: bool

In [26]:
# weather_df.set_index('DATE', inplace=True)
weather_df.head()

,STATION,NAME,DATE,AWND,PRCP,SNOW,SNWD,TMAX,TMIN,WDF2,...,WT09,WT11,WT13,WT14,WT15,WT16,WT17,WT18,WT21,WT22
0,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",2008-01-01,13.42,0.0,0.0,0.0,54,36,300,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",2008-01-02,18.34,0.0,0.0,0.0,38,25,330,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",2008-01-03,10.74,0.0,0.0,0.0,34,22,330,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",2008-01-04,5.82,0.0,0.0,0.0,41,21,170,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",2008-01-05,3.58,0.0,0.0,0.0,43,28,160,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [27]:
# lunar_df.set_index('Text', inplace=True)
# lunar_df.reset_index(inplace=True)
# lunar_df['Text'] = pd.to_datetime(lunar_df['Text'])

In [27]:
# lunar_df.set_index('DATE', inplace=True)
# lunar_df.drop(columns=['index'], inplace=True)
lunar_df.head()

         DATE  Day  Date  Month  Year  Illum
0  2008-01-01    3     1      1  2008   0.42
1  2008-02-01    4     2      1  2008   0.33
2  2008-03-01    5     3      1  2008   0.24
3  2008-04-01    6     4      1  2008   0.17
4  2008-05-01    7     5      1  2008   0.10

In [28]:
crime_df.head()

            CCN
START_DATE
2008-01-01   66
2008-01-02   66
2008-01-03   75
2008-01-04   65
2008-01-05   88

In [29]:
crime_df.reset_index(inplace=True)

In [30]:
crime_df.rename(columns={"START_DATE":"DATE"}, inplace=True)

In [31]:
crime_df.head()

         DATE  CCN
0  2008-01-01   66
1  2008-01-02   66
2  2008-01-03   75
3  2008-01-04   65
4  2008-01-05   88

In [32]:
crime_df.set_index('DATE', inplace=True)

In [33]:
crime_df.head()

            CCN
DATE
2008-01-01   66
2008-01-02   66
2008-01-03   75
2008-01-04   65
2008-01-05   88

In [34]:
lunar_df.reset_index(inplace=True)

In [35]:
lunar_df.rename(columns={"Text":"DATE"}, inplace=True)

In [36]:
lunar_df.set_index('DATE', inplace=True)
lunar_df.head()

            index  Day  Date  Month  Year  Illum
DATE
2008-01-01      0    3     1      1  2008   0.42
2008-02-01      1    4     2      1  2008   0.33
2008-03-01      2    5     3      1  2008   0.24
2008-04-01      3    6     4      1  2008   0.17
2008-05-01      4    7     5      1  2008   0.10

In [37]:
# lunar_df.to_csv('lunar_clean_08-20_sw.csv')
lunar_df.drop(columns=['index'], inplace=True)

In [38]:
weather_crime_df = pd.merge(crime_df, weather_df, on='DATE', how="left")

In [39]:
weather_crime_df.head()

,DATE,CCN,STATION,NAME,AWND,PRCP,SNOW,SNWD,TMAX,TMIN,...,WT09,WT11,WT13,WT14,WT15,WT16,WT17,WT18,WT21,WT22
0,2008-01-01,66,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",13.42,0.0,0.0,0.0,54.0,36.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2008-01-02,66,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",18.34,0.0,0.0,0.0,38.0,25.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,2008-01-03,75,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",10.74,0.0,0.0,0.0,34.0,22.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2008-01-04,65,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",5.82,0.0,0.0,0.0,41.0,21.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2008-01-05,88,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",3.58,0.0,0.0,0.0,43.0,28.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [40]:
weather_crime_lunar_df = pd.merge(weather_crime_df, lunar_df, on='DATE', how="left")

In [41]:
weather_crime_lunar_df

,DATE,CCN,STATION,NAME,AWND,PRCP,SNOW,SNWD,TMAX,TMIN,...,WT16,WT17,WT18,WT21,WT22,Day,Date,Month,Year,Illum
0,2008-01-01,66,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",13.42,0.00,0.0,0.0,54.0,36.0,...,0.0,0.0,0.0,0.0,0.0,3,1,1,2008,0.42
1,2008-01-02,66,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",18.34,0.00,0.0,0.0,38.0,25.0,...,0.0,0.0,1.0,0.0,0.0,6,1,2,2008,0.32
2,2008-01-03,75,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",10.74,0.00,0.0,0.0,34.0,22.0,...,0.0,0.0,0.0,0.0,0.0,7,1,3,2008,0.40
3,2008-01-04,65,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",5.82,0.00,0.0,0.0,41.0,21.0,...,0.0,0.0,0.0,0.0,0.0,3,1,4,2008,0.28
4,2008-01-05,88,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",3.58,0.00,0.0,0.0,43.0,28.0,...,1.0,0.0,0.0,0.0,0.0,5,1,5,2008,0.24
5,2008-01-06,63,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",2.91,0.20,0.0,0.0,55.0,38.0,...,1.0,0.0,0.0,0.0,0.0,1,1,6,2008,0.10
6,2008-01-07,87,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",8.50,0.00,0.0,0.0,69.0,46.0,...,0.0,0.0,0.0,0.0,0.0,3,1,7,2008,0.05
7,2008-01-08,88,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",11.18,0.00,0.0,0.0,73.0,48.0,...,0.0,0.0,0.0,0.0,0.0,6,1,8,2008,0.00
8,2008-01-09,79,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",11.86,0.00,0.0,0.0,68.0,47.0,...,0.0,0.0,0.0,0.0,0.0,2,1,9,2008,0.02
9,2008-01-10,56,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",3.80,0.18,0.0,0.0,52.0,40.0,...,1.0,0.0,0.0,0.0,0.0,4,1,10,2008,0.04
10,2008-01-11,82,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",4.47,0.15,0.0,0.0,59.0,43.0,...,1.0,0.0,0.0,0.0,0.0,7,1,11,2008,0.10
11,2008-01-12,75,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",6.93,0.00,0.0,0.0,54.0,42.0,...,0.0,0.0,0.0,0.0,0.0,2,1,12,2008,0.11
12,2008-01-13,90,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",6.93,0.03,0.0,0.0,49.0,36.0,...,1.0,0.0,0.0,0.0,0.0,1,13,1,2008,0.23
13,2008-01-14,64,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",8.50,0.00,0.0,0.0,47.0,35.0,...,1.0,0.0,1.0,0.0,0.0,2,14,1,2008,0.32
14,2008-01-15,94,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",8.95,0.00,0.0,0.0,40.0,30.0,...,0.0,0.0,1.0,0.0,0.0,3,15,1,2008,0.43
15,2008-01-16,73,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",7.61,0.00,0.0,0.0,44.0,32.0,...,0.0,0.0,0.0,0.0,0.0,4,16,1,2008,0.54
16,2008-01-17,82,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",6.26,0.75,1.3,0.0,39.0,34.0,...,1.0,0.0,1.0,0.0,0.0,5,17,1,2008,0.66
17,2008-01-18,112,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",6.71,0.00,0.0,1.0,49.0,33.0,...,1.0,0.0,0.0,0.0,0.0,6,18,1,2008,0.76
18,2008-01-19,92,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",6.93,0.00,0.0,0.0,42.0,36.0,...,0.0,0.0,1.0,0.0,0.0,7,19,1,2008,0.85
19,2008-01-20,76,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",15.21,0.00,0.0,0.0,37.0,19.0,...,0.0,0.0,0.0,0.0,0.0,1,20,1,2008,0.93
20,2008-01-21,82,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",7.38,0.00,0.0,0.0,32.0,18.0,...,0.0,0.0,0.0,0.0,0.0,2,21,1,2008,0.97
21,2008-01-22,97,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",11.18,0.00,0.0,0.0,42.0,26.0,...,1.0,0.0,0.0,0.0,0.0,3,22,1,2008,1.00
22,2008-01-23,98,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",9.17,0.00,0.0,0.0,48.0,30.0,...,0.0,0.0,0.0,0.0,0.0,4,23,1,2008,0.99
23,2008-01-24,100,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",9.84,0.00,0.0,0.0,43.0,28.0,...,0.0,0.0,0.0,0.0,0.0,5,24,1,2008,0.97
24,2008-01-25,100,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",9.62,0.00,0.0,0.0,36.0,22.0,...,0.0,0.0,0.0,0.0,0.0,6,25,1,2008,0.92
25,2008-01-26,110,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",5.14,0.00,0.0,0.0,40.0,29.0,...,0.0,0.0,0.0,0.0,0.0,7,26,1,2008,0.85
26,2008-01-27,93,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",8.28,0.00,0.0,0.0,45.0,30.0,...,0.0,0.0,0.0,0.0,0.0,1,27,1,2008,0.77
27,2008-01-28,106,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",7.16,0.00,0.0,0.0,47.0,33.0,...,0.0,0.0,0.0,0.0,0.0,2,28,1,2008,0.69
28,2008-01-29,108,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",4.03,0.05,0.0,0.0,54.0,33.0,...,1.0,0.0,0.0,0.0,0.0,3,29,1,2008,0.60
29,2008-01-30,80,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",15.43,0.01,0.0,0.0,56.0,36.0,...,1.0,0.0,0.0,0.0,0.0,4,30,1,2008,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4212,2019-07-14,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,14,7,2019,0.93
4213,2019-07-15,110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2,15,7,2019,0.97
4214,2019-07-16,84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3,16,7,2019,1.00
4215,2019-07-17,97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4,17,7,2019,1.00
4216,2019-07-18,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5,18,7,2019,0.98
4217,2019-07-19,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6,19,7,2019,0.95
4218,2019-07-20,95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,7,20,7,2019,0.90
4219,2019-07-21,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,21,7,2019,0.84
4220,2019-07-22,114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2,22,7,2019,0.76
4221,2019-07-23,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3,23,7,2019,0.68
4222,2019-07-24,104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4,24,7,2019,0.58
4223,2019-07-25,106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5,25,7,2019,0.49
4224,2019-07-26,122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6,26,7,2019,0.39
4225,2019-07-27,118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,7,27,7,2019,0.29
4226,2019-07-28,109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,28,7,2019,0.20
4227,2019-07-29,106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2,29,7,2019,0.12
4228,2019-07-30,123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3,30,7,2019,0.05
4229,2019-07-31,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4,31,7,2019,0.01
4230,2019-08-01,77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3,8,1,2019,0.04
4231,2019-08-02,85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6,8,2,2019,0.10
4232,2019-08-03,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6,8,3,2019,0.02
4233,2019-08-04,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2,8,4,2019,0.08
4234,2019-08-05,108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4,8,5,2019,0.12
4235,2019-08-06,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,7,8,6,2019,0.27
4236,2019-08-07,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2,8,7,2019,0.36
4237,2019-08-08,95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5,8,8,2019,0.55
4238,2019-08-09,94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,8,9,2019,0.71
4239,2019-08-10,85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3,8,10,2019,0.74
4240,2019-08-11,78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6,8,11,2019,0.83
4241,2019-08-12,93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,8,12,2019,0.84

In [42]:
weather_crime_lunar_df.isnull().any()

DATE       False
CCN        False
STATION     True
NAME        True
AWND        True
PRCP        True
SNOW        True
SNWD        True
TMAX        True
TMIN        True
WDF2        True
WDF5        True
WSF2        True
WSF5        True
WT01        True
WT02        True
WT03        True
WT04        True
WT05        True
WT06        True
WT07        True
WT08        True
WT09        True
WT11        True
WT13        True
WT14        True
WT15        True
WT16        True
WT17        True
WT18        True
WT21        True
WT22        True
Day        False
Date       False
Month      False
Year       False
Illum      False
dtype: bool

In [43]:
weather_crime_lunar_df.dropna(inplace=True)

In [44]:
weather_crime_lunar_df.reset_index(inplace=True)

In [45]:
weather_crime_lunar_df

,index,DATE,CCN,STATION,NAME,AWND,PRCP,SNOW,SNWD,TMAX,...,WT16,WT17,WT18,WT21,WT22,Day,Date,Month,Year,Illum
0,0,2008-01-01,66,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",13.42,0.00,0.0,0.0,54.0,...,0.0,0.0,0.0,0.0,0.0,3,1,1,2008,0.42
1,1,2008-01-02,66,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",18.34,0.00,0.0,0.0,38.0,...,0.0,0.0,1.0,0.0,0.0,6,1,2,2008,0.32
2,2,2008-01-03,75,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",10.74,0.00,0.0,0.0,34.0,...,0.0,0.0,0.0,0.0,0.0,7,1,3,2008,0.40
3,3,2008-01-04,65,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",5.82,0.00,0.0,0.0,41.0,...,0.0,0.0,0.0,0.0,0.0,3,1,4,2008,0.28
4,4,2008-01-05,88,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",3.58,0.00,0.0,0.0,43.0,...,1.0,0.0,0.0,0.0,0.0,5,1,5,2008,0.24
5,5,2008-01-06,63,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",2.91,0.20,0.0,0.0,55.0,...,1.0,0.0,0.0,0.0,0.0,1,1,6,2008,0.10
6,6,2008-01-07,87,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",8.50,0.00,0.0,0.0,69.0,...,0.0,0.0,0.0,0.0,0.0,3,1,7,2008,0.05
7,7,2008-01-08,88,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",11.18,0.00,0.0,0.0,73.0,...,0.0,0.0,0.0,0.0,0.0,6,1,8,2008,0.00
8,8,2008-01-09,79,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",11.86,0.00,0.0,0.0,68.0,...,0.0,0.0,0.0,0.0,0.0,2,1,9,2008,0.02
9,9,2008-01-10,56,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",3.80,0.18,0.0,0.0,52.0,...,1.0,0.0,0.0,0.0,0.0,4,1,10,2008,0.04
10,10,2008-01-11,82,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",4.47,0.15,0.0,0.0,59.0,...,1.0,0.0,0.0,0.0,0.0,7,1,11,2008,0.10
11,11,2008-01-12,75,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",6.93,0.00,0.0,0.0,54.0,...,0.0,0.0,0.0,0.0,0.0,2,1,12,2008,0.11
12,12,2008-01-13,90,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",6.93,0.03,0.0,0.0,49.0,...,1.0,0.0,0.0,0.0,0.0,1,13,1,2008,0.23
13,13,2008-01-14,64,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",8.50,0.00,0.0,0.0,47.0,...,1.0,0.0,1.0,0.0,0.0,2,14,1,2008,0.32
14,14,2008-01-15,94,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",8.95,0.00,0.0,0.0,40.0,...,0.0,0.0,1.0,0.0,0.0,3,15,1,2008,0.43
15,15,2008-01-16,73,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",7.61,0.00,0.0,0.0,44.0,...,0.0,0.0,0.0,0.0,0.0,4,16,1,2008,0.54
16,16,2008-01-17,82,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",6.26,0.75,1.3,0.0,39.0,...,1.0,0.0,1.0,0.0,0.0,5,17,1,2008,0.66
17,17,2008-01-18,112,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",6.71,0.00,0.0,1.0,49.0,...,1.0,0.0,0.0,0.0,0.0,6,18,1,2008,0.76
18,18,2008-01-19,92,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",6.93,0.00,0.0,0.0,42.0,...,0.0,0.0,1.0,0.0,0.0,7,19,1,2008,0.85
19,19,2008-01-20,76,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",15.21,0.00,0.0,0.0,37.0,...,0.0,0.0,0.0,0.0,0.0,1,20,1,2008,0.93
20,20,2008-01-21,82,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",7.38,0.00,0.0,0.0,32.0,...,0.0,0.0,0.0,0.0,0.0,2,21,1,2008,0.97
21,21,2008-01-22,97,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",11.18,0.00,0.0,0.0,42.0,...,1.0,0.0,0.0,0.0,0.0,3,22,1,2008,1.00
22,22,2008-01-23,98,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",9.17,0.00,0.0,0.0,48.0,...,0.0,0.0,0.0,0.0,0.0,4,23,1,2008,0.99
23,23,2008-01-24,100,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",9.84,0.00,0.0,0.0,43.0,...,0.0,0.0,0.0,0.0,0.0,5,24,1,2008,0.97
24,24,2008-01-25,100,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",9.62,0.00,0.0,0.0,36.0,...,0.0,0.0,0.0,0.0,0.0,6,25,1,2008,0.92
25,25,2008-01-26,110,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",5.14,0.00,0.0,0.0,40.0,...,0.0,0.0,0.0,0.0,0.0,7,26,1,2008,0.85
26,26,2008-01-27,93,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",8.28,0.00,0.0,0.0,45.0,...,0.0,0.0,0.0,0.0,0.0,1,27,1,2008,0.77
27,27,2008-01-28,106,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",7.16,0.00,0.0,0.0,47.0,...,0.0,0.0,0.0,0.0,0.0,2,28,1,2008,0.69
28,28,2008-01-29,108,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",4.03,0.05,0.0,0.0,54.0,...,1.0,0.0,0.0,0.0,0.0,3,29,1,2008,0.60
29,29,2008-01-30,80,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",15.43,0.01,0.0,0.0,56.0,...,1.0,0.0,0.0,0.0,0.0,4,30,1,2008,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4170,4170,2019-06-02,90,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",8.28,0.01,0.0,0.0,85.0,...,0.0,0.0,0.0,0.0,0.0,4,6,2,2019,0.02
4171,4171,2019-06-03,90,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",10.51,0.00,0.0,0.0,76.0,...,0.0,0.0,0.0,0.0,0.0,4,6,3,2019,0.00
4172,4172,2019-06-04,80,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",8.28,0.00,0.0,0.0,78.0,...,0.0,0.0,0.0,0.0,0.0,7,6,4,2019,0.01
4173,4173,2019-06-05,83,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",11.86,0.01,0.0,0.0,83.0,...,0.0,0.0,0.0,0.0,0.0,2,6,5,2019,0.02
4174,4174,2019-06-06,81,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",7.83,0.00,0.0,0.0,90.0,...,0.0,0.0,0.0,0.0,0.0,5,6,6,2019,0.10
4175,4175,2019-06-07,96,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",8.95,0.00,0.0,0.0,81.0,...,0.0,0.0,0.0,0.0,0.0,7,6,7,2019,0.16
4176,4176,2019-06-08,97,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",12.08,0.00,0.0,0.0,83.0,...,0.0,0.0,0.0,0.0,0.0,3,6,8,2019,0.33
4177,4177,2019-06-09,108,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",13.87,0.13,0.0,0.0,74.0,...,0.0,0.0,0.0,0.0,0.0,6,6,9,2019,0.51
4178,4178,2019-06-10,98,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",5.82,0.37,0.0,0.0,77.0,...,0.0,0.0,0.0,0.0,0.0,1,6,10,2019,0.55
4179,4179,2019-06-11,93,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",12.53,0.14,0.0,0.0,81.0,...,0.0,0.0,0.0,0.0,0.0,4,6,11,2019,0.67
4180,4180,2019-06-12,98,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",7.83,0.08,0.0,0.0,78.0,...,0.0,0.0,0.0,0.0,0.0,6,6,12,2019,0.68
4181,4181,2019-06-13,89,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",8.05,1.05,0.0,0.0,79.0,...,0.0,0.0,0.0,0.0,0.0,5,13,6,2019,0.81
4182,4182,2019-06-14,100,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",10.96,0.00,0.0,0.0,79.0,...,0.0,0.0,0.0,0.0,0.0,6,14,6,2019,0.89
4183,4183,2019-06-15,87,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",11.41,0.00,0.0,0.0,84.0,...,0.0,0.0,0.0,0.0,0.0,7,15,6,2019,0.95
4184,4184,2019-06-16,112,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",10.74,0.00,0.0,0.0,87.0,...,0.0,0.0,0.0,0.0,0.0,1,16,6,2019,0.98
4185,4185,2019-06-17,86,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",5.82,0.99,0.0,0.0,91.0,...,0.0,0.0,0.0,0.0,0.0,2,17,6,2019,1.00
4186,4186,2019-06-18,99,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",6.49,1.16,0.0,0.0,88.0,...,0.0,0.0,0.0,0.0,0.0,3,18,6,2019,0.99
4187,4187,2019-06-19,88,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",8.05,0.00,0.0,0.0,87.0,...,0.0,0.0,0.0,0.0,0.0,4,19,6,2019,0.97
4188,4188,2019-06-20,98,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",10.96,0.08,0.0,0.0,92.0,...,0.0,0.0,0.0,0.0,0.0,5,20,6,2019,0.92
4189,4189,2019-06-21,106,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",13.87,0.00,0.0,0.0,85.0,...,0.0,0.0,0.0,0.0,0.0,6,21,6,2019,0.86
4190,4190,2019-06-22,100,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",9.17,0.00,0.0,0.0,83.0,...,0.0,0.0,0.0,0.0,0.0,7,22,6,2019,0.79
4191,4191,2019-06-23,98,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",6.71,0.00,0.0,0.0,84.0,...,0.0,0.0,0.0,0.0,0.0,1,23,6,2019,0.70
4192,4192,2019-06-24,99,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",7.16,0.02,0.0,0.0,88.0,...,0.0,0.0,0.0,0.0,0.0,2,24,6,2019,0.61
4193,4193,2019-06-25,108,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",8.72,0.19,0.0,0.0,90.0,...,0.0,0.0,0.0,0.0,0.0,3,25,6,2019,0.52
4194,4194,2019-06-26,92,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",8.95,0.00,0.0,0.0,91.0,...,0.0,0.0,0.0,0.0,0.0,4,26,6,2019,0.42
4195,4195,2019-06-27,87,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",5.82,0.00,0.0,0.0,92.0,...,0.0,0.0,0.0,0.0,0.0,5,27,6,2019,0.33
4196,4196,2019-06-28,108,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",5.59,0.00,0.0,0.0,95.0,...,0.0,0.0,0.0,0.0,0.0,6,28,6,2019,0.24
4197,4197,2019-06-29,111,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",7.83,0.04,0.0,0.0,96.0,...,0.0,0.0,0.0,0.0,0.0,7,29,6,2019,0.16
4198,4198,2019-06-30,65,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",13.65,0.00,0.0,0.0,92.0,...,0.0,0.0,0.0,0.0,0.0,1,30,6,2019,0.09
4199,4199,2019-07-01,80,USW00013743,"WASHINGTON REAGAN NATIONAL AIRPORT, VA US",6.71,0.00,0.0,0.0,88.0,...,0.0,0.0,0.0,0.0,0.0,2,7,1,2019,0.01

In [46]:
weather_crime_lunar_df.to_csv("complete_weather_crime_lunar_08-19.csv")